### ISSUE TITLE
Want to help on the official meilisearch-dotnet repo? 😁

### ISSUE THREAD

**Issue by curquiza** [barbados-clemens/meilisearch-dotnet#1]
Hello @barbados-clemens!

I write here because I did not find your email on your GitHub profile!
I'm Clémentine, from the MeiliSearch team, and I can see you are coding a meilisearch-dotnet 🙂
Maybe you are doing this package for your own projects with your own needs, but if you are building a general wrapper for MeiliSearch in C#, here is the official [meilisearch-dotnet](https://github.com/meilisearch/meilisearch-dotnet) repo we maintain.
Every help on it would be appreciated! For example, we don't have an error handler on our official repo yet, and I can see you already integrated one on yours! 😁

If it's okay with you, feel free to join us to work on the official repo, it would be a pleasure to work with you!
Plus, here is [our Slack](https://meilicommunity.slack.com/join/shared_invite/zt-c4rs8tpi-ZId_q3fw~7cqeuzFG4XHaA#/) if you need direct chatting. I'm available to guide on every steps!

See you soon maybe on GitHub! 🚀

**Comment by barbados-clemens** [comment]
I didn't see that there was an official repo for dotnet yet! 
I was writing a general purpose one for use in my own projects and figured I'd help out. I'll remove this repo and start trying to help on the official one where I can. 

Thanks for reaching out. Looks like I need to put my email up to make it easier to contact!

Thanks!
